/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.college.view;

import lk.ijse.college.controller.CourseController;
import lk.ijse.college.dto.CourseDTO;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import lk.ijse.college.entity.Course;

/**
 *
 * @author dell
 */
public class CourseForm extends javax.swing.JFrame {

    /**
     * Creates new form CourseForm
     */
    public CourseForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCourseName2 = new javax.swing.JTextField();
        txtIntake = new javax.swing.JTextField();
        txtDuration = new javax.swing.JTextField();
        btnAddCourse = new javax.swing.JButton();
        lblId2 = new javax.swing.JLabel();
        txtCode = new javax.swing.JTextField();
        lblId3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel3.setText("Name");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel4.setText("Intake");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel5.setText("Duration");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        txtCourseName2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtCourseName2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCourseName2ActionPerformed(evt);
            }
        });
        jPanel3.add(txtCourseName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 170, 40));

        txtIntake.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtIntake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIntakeActionPerformed(evt);
            }
        });
        jPanel3.add(txtIntake, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 170, 40));

        txtDuration.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtDuration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDurationActionPerformed(evt);
            }
        });
        jPanel3.add(txtDuration, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 170, 40));

        btnAddCourse.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnAddCourse.setText("Add Course");
        btnAddCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCourseActionPerformed(evt);
            }
        });
        jPanel3.add(btnAddCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, -1, -1));

        lblId2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblId2.setText("Add Course");
        jPanel3.add(lblId2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 190, -1));

        txtCode.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodeActionPerformed(evt);
            }
        });
        jPanel3.add(txtCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 160, 40));

        lblId3.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        lblId3.setText("Course Code");
        jPanel3.add(lblId3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 110, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCourseName2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCourseName2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCourseName2ActionPerformed

    private void txtIntakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIntakeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIntakeActionPerformed

    private void txtDurationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDurationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDurationActionPerformed

    private void btnAddCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCourseActionPerformed
        try {
            String code=txtCode.getText();
            String courseName=txtCourseName2.getText();
            String intake=txtIntake.getText();
            String duration=txtDuration.getText();

            CourseDTO dto=new CourseDTO(courseName, courseName, intake, duration);
            CourseController controller=new CourseController();
            boolean isAdded=controller.addCourse(dto);
            if(isAdded){
                JOptionPane.showMessageDialog(this, "Course Added Successfully");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(RegistrationForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(RegistrationForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(RegistrationForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddCourseActionPerformed

    private void txtCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CourseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CourseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CourseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CourseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CourseForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCourse;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblId2;
    private javax.swing.JLabel lblId3;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtCourseName2;
    private javax.swing.JTextField txtDuration;
    private javax.swing.JTextField txtIntake;
    // End of variables declaration//GEN-END:variables
}
