/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vehicleparking;

import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class bookParkingForm extends javax.swing.JFrame {

    /**
     * Creates new form bookParkingForm
     */
    public bookParkingForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        assignText = new javax.swing.JButton();
        cashierText = new javax.swing.JButton();
        cancelText = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        noText = new javax.swing.JTextField();
        nameText = new javax.swing.JTextField();
        searchText1 = new javax.swing.JButton();
        registerText2 = new javax.swing.JButton();
        searchText = new javax.swing.JButton();
        registerText3 = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 0));
        jLabel1.setText("SunRise Shopping Complex");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jButton1.setText("jButton1");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, -1, -1));

        jPasswordField1.setText("jPasswordField1");

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Desktop\\rozen.jpg")); // NOI18N
        jLabel6.setText("jLabel6");
        jLabel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(102, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Parchment", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 255));
        jLabel3.setText("SunRise Shopping Complex");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        assignText.setBackground(new java.awt.Color(204, 204, 204));
        assignText.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        assignText.setForeground(new java.awt.Color(153, 0, 51));
        assignText.setText("Assign Parking");
        assignText.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        assignText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignTextActionPerformed(evt);
            }
        });
        jPanel2.add(assignText, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 110, 30));

        cashierText.setBackground(new java.awt.Color(204, 204, 204));
        cashierText.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cashierText.setForeground(new java.awt.Color(153, 0, 51));
        cashierText.setText("Cashier's Form");
        cashierText.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cashierText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashierTextActionPerformed(evt);
            }
        });
        jPanel2.add(cashierText, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 110, 30));

        cancelText.setBackground(new java.awt.Color(204, 204, 204));
        cancelText.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        cancelText.setForeground(new java.awt.Color(153, 0, 51));
        cancelText.setText("Cancel");
        cancelText.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cancelText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelTextActionPerformed(evt);
            }
        });
        jPanel2.add(cancelText, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 370, 50, 30));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setForeground(new java.awt.Color(102, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 0));
        jLabel2.setText("Vehicle Number");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, 20));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 0));
        jLabel5.setText("Owner's Name");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, 20));

        noText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noTextActionPerformed(evt);
            }
        });
        jPanel3.add(noText, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 380, 30));

        nameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextActionPerformed(evt);
            }
        });
        jPanel3.add(nameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 380, 30));

        searchText1.setBackground(new java.awt.Color(204, 204, 204));
        searchText1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        searchText1.setForeground(new java.awt.Color(153, 0, 51));
        searchText1.setText("Search Vehicle");
        searchText1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        searchText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchText1ActionPerformed(evt);
            }
        });
        jPanel3.add(searchText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 110, 30));

        registerText2.setBackground(new java.awt.Color(204, 204, 204));
        registerText2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        registerText2.setForeground(new java.awt.Color(153, 0, 51));
        registerText2.setText("Register Vehicle");
        registerText2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        registerText2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerText2ActionPerformed(evt);
            }
        });
        jPanel3.add(registerText2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 110, 30));

        searchText.setBackground(new java.awt.Color(204, 204, 204));
        searchText.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        searchText.setForeground(new java.awt.Color(153, 0, 51));
        searchText.setText("Search Vehicle");
        searchText.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        searchText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTextActionPerformed(evt);
            }
        });
        jPanel3.add(searchText, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 110, 30));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 760, 210));

        registerText3.setBackground(new java.awt.Color(204, 204, 204));
        registerText3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        registerText3.setForeground(new java.awt.Color(153, 0, 51));
        registerText3.setText("Register Vehicle");
        registerText3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        registerText3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerText3ActionPerformed(evt);
            }
        });
        jPanel2.add(registerText3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 110, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelTextActionPerformed
        dispose();
    }//GEN-LAST:event_cancelTextActionPerformed

    private void cashierTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashierTextActionPerformed
        cashierPaymentForm cashier=new cashierPaymentForm();
        cashier.setVisible(true);
    }//GEN-LAST:event_cashierTextActionPerformed

    private void assignTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignTextActionPerformed
        AssignParkingForm assign=new AssignParkingForm();
        assign.setVisible(true);
    }//GEN-LAST:event_assignTextActionPerformed

    private void registerText3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerText3ActionPerformed
        String vNo = noText.getText();
       String ownerName = nameText.getText();
       
      try {
          
            boolean isAdded = VehicleController.addVehicle(vNo, ownerName);
            if (isAdded) {
                JOptionPane.showMessageDialog(this, "Vehicle added successfully");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Driver not found");
        }
      
    }//GEN-LAST:event_registerText3ActionPerformed

    private void searchTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTextActionPerformed
        try {
            Vehicle vehicle=VehicleController.searchVehicle(noText.getText());
            if(vehicle!=null){

                nameText.setText(vehicle.getOwnerName());

            }else{
                JOptionPane.showMessageDialog(this, "Vehicle not found...");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Driver not found...");
        }
    }//GEN-LAST:event_searchTextActionPerformed

    private void registerText2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerText2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerText2ActionPerformed

    private void searchText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchText1ActionPerformed

    }//GEN-LAST:event_searchText1ActionPerformed

    private void nameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextActionPerformed

    private void noTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noTextActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_noTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bookParkingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bookParkingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bookParkingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bookParkingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bookParkingForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignText;
    private javax.swing.JButton cancelText;
    private javax.swing.JButton cashierText;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField nameText;
    private javax.swing.JTextField noText;
    private javax.swing.JButton registerText2;
    private javax.swing.JButton registerText3;
    private javax.swing.JButton searchText;
    private javax.swing.JButton searchText1;
    // End of variables declaration//GEN-END:variables
}
