/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vehicleparking;

import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class cashierPaymentForm extends javax.swing.JFrame {

    /**
     * Creates new form cashierPaymentForm
     */
    public cashierPaymentForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cancelText1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        typeText = new javax.swing.JTextField();
        departureText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        arrivalText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        feeText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        timeText = new javax.swing.JTextField();
        paymentText1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        methodOne = new javax.swing.JComboBox<>();
        feeBtn = new javax.swing.JButton();
        paymentText = new javax.swing.JTextField();
        timeBtn = new javax.swing.JButton();
        saveText2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        noText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        detailText = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cancelText1.setBackground(new java.awt.Color(204, 204, 204));
        cancelText1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        cancelText1.setForeground(new java.awt.Color(153, 0, 51));
        cancelText1.setText("Cancel");
        cancelText1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cancelText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelText1ActionPerformed(evt);
            }
        });
        jPanel1.add(cancelText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 460, 50, 30));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 0));
        jLabel2.setText("Vehicle Type");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, 20));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 0));
        jLabel4.setText("Departure Time");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, 20));

        typeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeTextActionPerformed(evt);
            }
        });
        jPanel3.add(typeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 380, 30));
        jPanel3.add(departureText, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 380, 30));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 0, 0));
        jLabel6.setText("Arrival Time");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, 20));
        jPanel3.add(arrivalText, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 380, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 0));
        jLabel5.setText("Total Fee");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, 20));
        jPanel3.add(feeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, 240, 30));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 0, 0));
        jLabel7.setText("Total Time");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, 20));
        jPanel3.add(timeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 240, 30));

        paymentText1.setBackground(new java.awt.Color(204, 204, 204));
        paymentText1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        paymentText1.setForeground(new java.awt.Color(153, 0, 51));
        paymentText1.setText("Do Payment");
        paymentText1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        paymentText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentText1ActionPerformed(evt);
            }
        });
        jPanel3.add(paymentText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 140, 40));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 0));
        jLabel1.setText("Payment Method");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, -1));

        methodOne.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        methodOne.setForeground(new java.awt.Color(102, 0, 0));
        methodOne.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Card" }));
        methodOne.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        methodOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                methodOneActionPerformed(evt);
            }
        });
        jPanel3.add(methodOne, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 90, 30));

        feeBtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        feeBtn.setForeground(new java.awt.Color(102, 0, 0));
        feeBtn.setText("Calculate Fee");
        feeBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        feeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feeBtnActionPerformed(evt);
            }
        });
        jPanel3.add(feeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 130, 30));
        jPanel3.add(paymentText, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 240, 30));

        timeBtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        timeBtn.setForeground(new java.awt.Color(102, 0, 0));
        timeBtn.setText("Calculate Time");
        timeBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        timeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeBtnActionPerformed(evt);
            }
        });
        jPanel3.add(timeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 130, 30));

        saveText2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        saveText2.setForeground(new java.awt.Color(102, 0, 0));
        saveText2.setText("Save");
        saveText2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        saveText2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveText2ActionPerformed(evt);
            }
        });
        jPanel3.add(saveText2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 60, 30));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 0, 0));
        jLabel8.setText("Vehicle Number");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, 20));

        noText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noTextActionPerformed(evt);
            }
        });
        jPanel3.add(noText, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 380, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 770, 350));

        jLabel3.setFont(new java.awt.Font("Parchment", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 255));
        jLabel3.setText("SunRise Shopping Complex");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        detailText.setBackground(new java.awt.Color(204, 204, 204));
        detailText.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        detailText.setForeground(new java.awt.Color(153, 0, 51));
        detailText.setText("View Details");
        detailText.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        detailText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailTextActionPerformed(evt);
            }
        });
        jPanel1.add(detailText, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, 140, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelText1ActionPerformed
        // TODO add your handling code here
        dispose();
    }//GEN-LAST:event_cancelText1ActionPerformed

    private void typeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeTextActionPerformed
        
    }//GEN-LAST:event_typeTextActionPerformed

    private void detailTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailTextActionPerformed
       ViewDetailForm view=new ViewDetailForm();
        view.setVisible(true);
    }//GEN-LAST:event_detailTextActionPerformed

    private void paymentText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentText1ActionPerformed
       String vNo = noText.getText();
       String vType = typeText.getText();
       double arrivalTime = Double.parseDouble(arrivalText.getText());     
       double departureTime = Double.parseDouble(departureText.getText());
       double parkedTime = Double.parseDouble(timeText.getText()); 
       double totalFee = Double.parseDouble(feeText.getText()); 
       String payment = paymentText.getText(); 
        try {
          
            boolean isAdded = VehicleController.addPayment(vNo, vType, arrivalTime, departureTime, parkedTime, totalFee, payment);
            if (isAdded) {
                JOptionPane.showMessageDialog(this, "Payment done successfully");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Driver not found");
        }
    }//GEN-LAST:event_paymentText1ActionPerformed

    private void feeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feeBtnActionPerformed
      double a1=Double.parseDouble(arrivalText.getText());
       double a2=Double.parseDouble(departureText.getText());
       double hours=a2-a1;
       String type=typeText.getText();
       double total=0.00;
       if(type.contains("Car")){
           total=hours*50.00;  
            feeText.setText(Double.toString(total));
       }else if(type.contains("Van")){
           total=hours*75.00;  
            feeText.setText(Double.toString(total));
       }else if(type.contains("Bus")){
           total=hours*100.00;  
            feeText.setText(Double.toString(total));
       }else if(type.contains("Lorry")){
           total=hours*150.00;  
            feeText.setText(Double.toString(total));
       }        

      
        
        
       
           
        
        
       
    }//GEN-LAST:event_feeBtnActionPerformed

    private void timeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeBtnActionPerformed
       double a1=Double.parseDouble(arrivalText.getText());
       double a2=Double.parseDouble(departureText.getText());
       double hours=a2-a1;
        timeText.setText(Double.toString(hours));
        
    }//GEN-LAST:event_timeBtnActionPerformed

    private void saveText2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveText2ActionPerformed
       
    }//GEN-LAST:event_saveText2ActionPerformed

    private void noTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noTextActionPerformed
           try {
            Parking parking=VehicleController.searchParking(noText.getText());
            if(parking!=null){
                
                typeText.setText(parking.getvType());
               
                arrivalText.setText(parking.getArrivalTime()+"");
               
                
            }else{
                JOptionPane.showMessageDialog(this, "Vehicle not found...");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(this, "Driver not found...");
        }
    }//GEN-LAST:event_noTextActionPerformed

    private void methodOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_methodOneActionPerformed
       String item=(String)methodOne.getSelectedItem();

        paymentText.setText(item);
    }//GEN-LAST:event_methodOneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cashierPaymentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cashierPaymentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cashierPaymentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cashierPaymentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cashierPaymentForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField arrivalText;
    private javax.swing.JButton cancelText1;
    private javax.swing.JTextField departureText;
    private javax.swing.JButton detailText;
    private javax.swing.JButton feeBtn;
    private javax.swing.JTextField feeText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JComboBox<String> methodOne;
    private javax.swing.JTextField noText;
    private javax.swing.JTextField paymentText;
    private javax.swing.JButton paymentText1;
    private javax.swing.JButton saveText2;
    private javax.swing.JButton timeBtn;
    private javax.swing.JTextField timeText;
    private javax.swing.JTextField typeText;
    // End of variables declaration//GEN-END:variables
}
